language: python
cache: pip
install:
- pip install -r requirements.txt
script: mkdocs build --clean
deploy:
  provider: pages
  local-dir: site/
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
notifications:
  slack:
    secure: ZGakr+ZCLaKlZGCZLGP13c6060T6Sw8Kh17GcNaTgCpFPbPQqWBZojcbPBanz59z9eEHYeh4bsMbTHCs3wkfX5NZOQD/HoG9E/4DcbTSOSTdOyyxLU66+qIDmzb9B1BWFiB+FZRqQcST9zifmXUYo3e1CTdBzhHzGsRO18U1tXBSPabRiVtROkwMwuX7RwW2KCpasVc3k7YvJG96ChrfTl/3ZClN13/2nnO2UcDot8+yz2aqgJB6YA0G5QihQvE/0S1FCxePHrtoOlzMSY53txiS28QQusE9Q/O5C7EJWddx14wiUgqqLfwPAAnV/hnTywjlQHT1Vjfflj1PxSN+t1M+r4MLTGjiUXZA78U0R1ZZ5/RzzynLe/Np0pAKHqrNveUQTzPXgZ02HCtqlvs5nPdTYeHhm7tTMR72dr2AsQ37ZRRIqTze5mX72qsmNrk4futC/tjn39mM/UMuu1sLsxwz1zuxRL1Qqg9jIpMyxwMHBmjXZfqnLLUWTjXLVAOVmwlJD4pt5Qj67p+COoXlJUx3wCxD4GbcF8ucom//gK2o1b2bOyxaKUS0GM6raLG2d4ZHVxloYGicYF4ilMjTvtjM/UhPlOrgWdp3McNM4BWdSTpGevUvyEYLdau//GgEKi9nfbo/TMGl/c9csmh90Oa2FlnJxSmzeSNFVW6ye3g=
