site_name: FEATHER
site_description: Team 1540's Free Easy-Access Team Handbook for Efficient Robotics.
site_author: FRC Team 1540, The Flaming Chickens
site_url: https://robinsonz.github.io/readthedocs-test/

repo_name: robinsonz/readthedocs-test
repo_url: https://github.com/robinsonz/readthedocs-test/
edit_uri: blob/master/docs/

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'blue'
    accent: 'amber'
  feature:
    tabs: true
  logo: 'images/feather.svg'

extra:
  social:
    - type: 'globe'
      link: 'https://team1540.org'
    - type: 'github'
      link: 'https://github.com/flamingchickens1540'
    - type: 'facebook'
      link: 'https://www.facebook.com/FRC1540/'
    - type: 'twitter'
      link: 'https://twitter.com/flamingchickens'
    - type: 'instagram'
      link: 'https://www.instagram.com/1540flamingchickens/'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret

# Required for Arithmatex extension (https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#loading-mathjax)
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - 'css/key-icons.css'

pages:
    - Home:
      - Welcome to FEATHER: index.md
      - Attribution: legal.md
    - Markdown Demos:
      - First Demo: demos/about.md
      - Second Demo: demos/more-testing.md
      - Tutorial: demos/tutorial.md
    - Guides:
      - PID Tuning: guides/velocity-pid.md
      - Debugging Robot Code: guides/debugging-robot-code.md
    - Reference Sheet:
      - Getting Started: refsheet/getting-started.md
      - Useful Links: refsheet/links.md
