site_name: FEATHER

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'orange'
  feature:
    tabs: true
  logo: 'images/feather.svg'
  extra:
    social:
      - type: 'globe'
        link: 'https://team1540.org'
      - type: 'github'
        link: 'https://github.com/flamingchickens1540'
      - type: 'twitter'
        link: 'https://twitter.com/flamingchickens'
      - type: 'facebook'
        link: 'https://www.facebook.com/FRC1540/'
      - type: 'instagram'
        link: 'https://www.instagram.com/1540flamingchickens/'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde